services:
  - type: web
    name: gepn-backend
    env: go
    buildCommand: go mod download && go build -tags netgo -ldflags '-s -w' -o app
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: gepn

